name: SAP Tools
version: "4.4.0"
slug: simple_hello_world
description: SAP GUID converter and deep link generator for ByD, CRM and C4C v2 objects
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: manual
init: false
ingress: true
ingress_port: 3000
panel_icon: mdi:briefcase
panel_title: SAP Tools
panel_admin: false
options:
  dev_domain: dev-tenant.crm.ondemand.com
  acc_domain: acc-tenant.crm.ondemand.com
  prd_domain: prd-tenant.crm.ondemand.com
  crm_dev_domain: crm-dev.example.com:8443
  crm_acc_domain: crm-acc.example.com:8443
  crm_prd_domain: crm-prd.example.com:8443
  c4cv2_dev_domain: dev-tenant.de1.test.crm.cloud.sap
  c4cv2_acc_domain: acc-tenant.de1.test.crm.cloud.sap
  c4cv2_prd_domain: prd-tenant.de1.crm.cloud.sap
  crm_roles:
    - "ROLE_ID_1:Role Label 1"
    - "ROLE_ID_2:Role Label 2"
schema:
  dev_domain: str
  acc_domain: str
  prd_domain: str
  crm_dev_domain: str
  crm_acc_domain: str
  crm_prd_domain: str
  c4cv2_dev_domain: str
  c4cv2_acc_domain: str
  c4cv2_prd_domain: str
  crm_roles:
    - str
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armhf: "ghcr.io/home-assistant/armhf-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
  i386: "ghcr.io/home-assistant/i386-base:3.19"
